version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
      - devnet
    image: blockscout/blockscout:latest
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'ganache'
        ETHEREUM_JSONRPC_HTTP_URL: http://devnet:8545
        ETHEREUM_JSONRPC_WS_URL: ws://devnet:8545
        # INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
        # INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: "false"
        FIRST_BLOCK: "2428843"
    ports:
      - 4000:4000

  devnet:
    build:
      context: ./devnet
    ports:
      - 8545:8545
